##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 3861 2006-10-14 18:13:25Z LukeHodkinson $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_tst = libStGermainDiscretisationMesh

def_srcs = \
	testCommTopology.c \
	testDecomp.c \
	testDecomp_Sync.c \
	testDecompTransfer.c \
	testMeshTopology.c \
	testCartesianGenerator.c \
	testQuadEL.c \
	testParallelPipedQuadEL.c \
	testHexaEL.c \
	testParallelPipedHexaEL.c \
	testIrregEL.c \
	testHexaMD.c \
	testMesh.c \
	testMesh-large.c \
	testMeshSync.c \
	testMeshSync-2D.c \
	testMeshSync-large.c \

def_checks = \
	testDecomp.0of1.sh \
	testDecomp.0of2.sh \
	testDecomp.1of2.sh \
	testDecomp.0of3.sh \
	testDecomp.1of3.sh \
	testDecomp.2of3.sh \
	testDecomp.0of4.sh \
	testDecomp.1of4.sh \
	testDecomp.2of4.sh \
	testDecomp.3of4.sh \
	testQuadEL.0of1.sh \
	testParallelPipedQuadEL.0of1.sh \
	testParallelPipedQuadEL.0of2.sh \
	testParallelPipedQuadEL.1of2.sh \
	testParallelPipedQuadEL.0of3.sh \
	testParallelPipedQuadEL.1of3.sh \
	testParallelPipedQuadEL.2of3.sh \
	testHexaEL.0of1.sh \
	testParallelPipedHexaEL.0of1.sh \
	testParallelPipedHexaEL.0of2.sh \
	testParallelPipedHexaEL.1of2.sh \
	testParallelPipedHexaEL.0of3.sh \
	testParallelPipedHexaEL.1of3.sh \
	testParallelPipedHexaEL.2of3.sh \
	testIrregEL.0of1.sh \
	testHexaMD.0of1.sh \
	testHexaMD.0of2.sh \
	testHexaMD.1of2.sh \
	testHexaMD.0of3.sh \
	testHexaMD.1of3.sh \
	testHexaMD.2of3.sh \
	testHexaMD-shadowDepth2.0of2.sh \
	testHexaMD-shadowDepth2.1of2.sh \
	testHexaMD-shadowDepth2.0of3.sh \
	testHexaMD-shadowDepth2.1of3.sh \
	testHexaMD-2D_Decomp.0of4.sh \
	testHexaMD-2D_Decomp.1of4.sh \
	testHexaMD-2D_Decomp.2of4.sh \
	testHexaMD-2D_Decomp.3of4.sh \
	testHexaMD-3D_Decomp.0of8.sh \
	testHexaMD-3D_Decomp.7of8.sh \
	testHexaMD-2D_Decomp-shadowDepth2.0of4.sh \
	testHexaMD-2D_Decomp-shadowDepth2.1of4.sh \
	testHexaMD-2D_Decomp-shadowDepth2.2of4.sh \
	testHexaMD-2D_Decomp-shadowDepth2.3of4.sh \
	testHexaMD-3D_Decomp-shadowDepth2.0of8.sh \
	testHexaMD-3D_Decomp-shadowDepth2.7of8.sh \
	testHexaMD-unbalanced.0of4.sh \
	testHexaMD-unbalanced.1of4.sh \
	testHexaMD-unbalanced.2of4.sh \
	testHexaMD-unbalanced.3of4.sh \
	testHexaMD-unbalanced-shadowDepth2.0of4.sh \
	testHexaMD-unbalanced-shadowDepth2.1of4.sh \
	testHexaMD-unbalanced-shadowDepth2.2of4.sh \
	testHexaMD-unbalanced-shadowDepth2.3of4.sh \
	testHexaMD-periodic.0of2.sh \
	testHexaMD-periodic.1of2.sh \
	testHexaMD-periodic-shadowDepth2.0of2.sh \
	testHexaMD-periodic-shadowDepth2.1of2.sh \
	testMesh.0of1.sh \
	testMesh.0of2.sh \
	testMesh.1of2.sh \
	testMesh.0of3.sh \
	testMesh.1of3.sh \
	testMesh.2of3.sh \
	testMesh-large.0of1.sh \
	testMesh-large.0of4.sh \
	testMeshSync.0of3.sh \
	testMeshSync.1of3.sh \
	testMeshSync.2of3.sh \
	testMeshSync-2D.0of4.sh \
	testMeshSync-2D.1of4.sh \
	testMeshSync-2D.2of4.sh \
	testMeshSync-2D.3of4.sh \

