##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 3728 2006-07-31 03:14:51Z KathleenHumble $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_tst = libStGermainDiscretisationGeometry

def_srcs = \
	testDimensionMacros.c \
	testVectorMath.c \
	testTensorMath.c \
	testTrigMath.c \
	testComplexMath.c \
	testEdge.c \
	testPlane.c \
	testLine.c \
	testRMatrix.c \
	testBlockGeometry.c \
	testRefinedRegionsGeometry.c \
	testShellGeometry.c \
	testIrregGeometry.c \
	testIJK6Topology.c \
	testIJK26Topology.c \
	testDelaunay.c \
	testParallelDelaunay.c \
	testComplexVectorMath.c \
	testTensorMultMath.c
#	testFullTensorMath.c \
	
def_checks = \
	testDimensionMacros.0of1.sh \
	testVectorMath.0of1.sh \
	testTensorMath.0of1.sh \
	testTrigMath.0of1.sh \
	testComplexMath.0of1.sh \
	testEdge.0of1.sh \
	testPlane.0of1.sh \
	testLine.0of1.sh \
	testBlockGeometry.0of1.sh \
	testRefinedRegionsGeometry.0of1.sh \
	testShellGeometry.0of1.sh \
	testIrregGeometry.0of1.sh \
	testIJK6Topology.0of1.sh \
	testIJK26Topology.0of1.sh \
	testDelaunay.0of1.sh \
	testParallelDelaunay.0of1.sh \
	testParallelDelaunay.0of2.sh \
	testComplexVectorMath.0of1.sh \
	testTensorMultMath.0of1.sh \
#	testFullTensorMath.0of1.sh \
