##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 3512 2006-04-03 01:04:54Z AlanLo $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_tst = libStGermainBaseFoundation

def_test_support_srcs = \
	JournalWrappers.c \
	BTreeWrappers.c \
	PtrMapWrappers.c

def_srcs = \
	testMemory2DArray.c \
	testMemory2DArrayAs1D.c \
	testMemory2DComplex.c \
	testMemory3DArray.c \
	testMemory3DArrayAs1D.c \
	testMemory3DComplex.c \
	testMemory4DArray.c \
	testMemory4DArrayAs1D.c \
	testMemoryRealloc.c \
	testObjectList.c \
	testNamedObject_Register.c \
	testCommonRoutines.c \
	testTimeMonitor.c \
	testMemMonitor.c \
	testPrimitiveObject.c \
	testStg_asprintf.c

def_checks = \
	testObjectList.0of1.sh \
	testNamedObject_Register.0of1.sh \
	testTimeMonitor.0of1.sh \
	testCommonRoutines.0of1.sh \
	testPrimitiveObject.0of1.sh

ifdef USE_MEMORY_STATS
	def_srcs += \
		testMemory0.c \
		testMemory1.c \
		testMemory2.c 

	def_checks += \
		testMemory0.0of1.sh \
		testMemory1.0of1.sh \
		testMemory2.0of1.sh \
		testMemory2DArray.0of1.sh \
		testMemory2DArrayAs1D.0of1.sh \
		testMemory2DComplex.0of1.sh \
		testMemory3DArray.0of1.sh \
		testMemory3DArrayAs1D.0of1.sh \
		testMemory3DComplex.0of1.sh \
		testMemory4DArray.0of1.sh \
		testMemory4DArrayAs1D.0of1.sh \
		testMemoryRealloc.0of1.sh \
		testMemMonitor.0of1.sh \
		testMemMonitor.0of2.sh 
endif	

