##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 3728 2006-07-31 03:14:51Z KathleenHumble $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_lib = StGermainDiscretisationGeometry
def_inc = StGermain/Discretisation/Geometry

def_srcs = \
	Dimension.c \
	VectorMath.c \
	TensorMath.c \
	TrigMath.c \
	ComplexMath.c \
	Line.c \
	Plane.c \
	Edge.c \
	RMatrix.c \
	Topology.c \
	IJKTopology.c \
	IJK6Topology.c \
	IJK26Topology.c \
	IrregTopology.c \
	GeometryClass.c \
	BlockGeometry.c \
	RefinedRegionsGeometry.c \
	ShellGeometry.c \
	IrregGeometry.c \
	QuadEdge.c \
	Delaunay.c \
	ParallelDelaunay.c \
	Init.c \
	Finalise.c \
	ComplexVectorMath.c \
	TensorMultMath.c
#	FullTensorMath.c \


def_hdrs = \
	units.h \
	types.h \
	isinf.h \
	Dimension.h \
	VectorMath.h \
	TensorMath.h \
	TrigMath.h \
	ComplexMath.h \
	Line.h \
	Plane.h \
	Edge.h \
	RMatrix.h \
	Topology.h \
	IJKTopology.h \
	IJK6Topology.h \
	IJK26Topology.h \
	IrregTopology.h \
	GeometryClass.h \
	ShellGeometry.h \
	BlockGeometry.h \
	RefinedRegionsGeometry.h \
	IrregGeometry.h \
	QuadEdge.h \
	Delaunay.h \
	ParallelDelaunay.h \
	Init.h \
	Finalise.h \
	Geometry.h \
	ComplexVectorMath.h \
	stg_lapack.h \
	TensorMultMath.h	
#	FullTensorMath.h \

def_objlists =
