##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 3784 2006-09-06 10:01:39Z RaquibulHassan $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_lib = StGermainBaseContainer
def_inc = StGermain/Base/Container

def_srcs = \
	MPIRoutines.c \
	IndexSet.c \
	PtrMap.c \
	IndexMap.c \
	List.c \
	Array.c \
	UniqueList.c \
	BTreeNode.c \
	BTree.c \
	BTreeIterator.c \
	UIntMap.c \
	RangeSet.c \
	LinkedListNode.c \
	LinkedList.c \
	LinkedListIterator.c \
	HashTable.c \
	Set.c \
	PtrSet.c \
	Map.c \
	Heap.c \
	MaxHeap.c \
	MemoryPool.c \
	Init.c \
	Finalise.c

def_hdrs = \
	units.h \
	types.h \
	MPIRoutines.h \
	BTreeNode.h \
	BTree.h \
	BTreeIterator.h \
	UIntMap.h \
	RangeSet.h \
	LinkedListNode.h \
	LinkedList.h \
	LinkedListIterator.h \
	HashTable.h \
	IndexSet.h \
	PtrMap.h \
	IndexMap.h \
	List.h \
	Array.h \
	UniqueList.h \
	Set.h \
	PtrSet.h \
	Map.h \
	Heap.h \
	MaxHeap.h \
	MemoryPool.h \
	Init.h \
	Finalise.h \
	Container.h

def_objlists = 
