##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, 
##	Steve Quenette, 110 Victoria Street, Melbourne, Victoria, 3053, Australia.
##	Californian Institute of Technology, 1200 East California Boulevard, Pasadena, California, 91125, USA.
##	University of Texas, 1 University Station, Austin, Texas, 78712, USA.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Stevan M. Quenette, Visitor in Geophysics, Caltech.
##	Luc Lavier, Research Scientist, The University of Texas. (luc@utig.ug.utexas.edu)
##	Luc Lavier, Research Scientist, Caltech.
##
## This program is free software; you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by the
## Free Software Foundation; either version 2, or (at your option) any
## later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
## $Id: Makefile.def 3173 2005-11-21 23:47:09Z LukeHodkinson $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
def_lib = Snac
def_inc = Snac

def_srcs = \
	Material.c \
	Node.c \
	Mesh.c \
	Tetrahedra.c \
	TetrahedraTables.c \
	Element.c \
	EntryPoint.c \
	UpdateElement.c \
	StrainRate.c \
	Stress.c \
	Force.c \
	UpdateNode.c \
	Parallel.c \
	Context.c \
	SnacSync.c \
	Init.c \
	Finalise.c

def_hdrs = \
	units.h \
	types.h \
	shortcuts.h \
	Material.h \
	Node.h \
	Mesh.h \
	Tetrahedra.h \
	TetrahedraTables.h \
	Element.h \
	EntryPoint.h \
	UpdateElement.h \
	StrainRate.h \
	Stress.h \
	Force.h \
	UpdateNode.h \
	Context.h \
	SnacSync.h \
	Snac.h \
	Init.h \
	Finalise.h

