##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 1735 2004-07-26 00:19:55Z SteveQuenette $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_lib = StGermainBaseAutomation
def_inc = StGermain/Base/Automation

def_srcs = \
	Variable.c \
	Variable_Register.c \
	VariableDumpStream.c \
	ConditionFunction.c \
	ConditionFunction_Register.c \
	VariableCondition.c \
	VariableCondition_Register.c \
	CompositeVC.c \
	SetVC.c \
	VariableAllVC.c \
	Stg_Component.c \
	Stg_ComponentMeta.c \
	Stg_ComponentRegister.c \
	LiveComponentRegister.c \
	Stg_ComponentFactory.c \
	DocumentationComponentFactory.c \
	HierarchyTable.c \
	CallGraph.c \
	Init.c \
	Finalise.c

def_hdrs = \
	Variable.h \
	Variable_Register.h \
	VariableDumpStream.h \
	ConditionFunction.h \
	ConditionFunction_Register.h \
	VariableCondition.h \
	VariableCondition_Register.h \
	CompositeVC.h \
	SetVC.h \
	VariableAllVC.h \
	types.h \
	shortcuts.h \
	offsets.h \
	Stg_Component.h \
	Stg_ComponentMeta.h \
	Stg_ComponentRegister.h \
	LiveComponentRegister.h \
	Stg_ComponentFactory.h \
	DocumentationComponentFactory.h \
	HierarchyTable.h \
	CallGraph.h \
	Init.h \
	Finalise.h \
	Automation.h

def_objlists =
